#!/bin/bash

source .git/hooks/vars.sh

# Create temporary backup directory
mkdir -p "$TMP_BACKUP_DIR"

# Search for files containing the marked blocks
files_with_blocks=$(git diff --name-only --pickaxe-regex --cached -S"$start_mark|$line_mark" | grep -v "$HOOKS_DIR")

for file in $files_with_blocks; do
    # Backup the original file to temporary directory
    cp --parents "$file" "$TMP_BACKUP_DIR/"

    # Remove unstaged changes
    git restore "$file"

    # Remove marked blocks/lines from the source file
    sed -i -e "/$start_mark/,/$end_mark/d" -e "/$line_mark/d" "$file"

    # Stage the updated file
    git add "$file"

    # Restore original file
    mv "$TMP_BACKUP_DIR/$file" "$file"
done

# Remove temporary backup directory
rm -rf "$TMP_BACKUP_DIR"
